stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - cat /etc/*ele*
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python3 get-pip.py
    - pip install setuptools
  script: pip install .

test:
  stage: test
  before_script:
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python3 get-pip.py
    - pip install setuptools
    - pip install .
  script: zuserver & sleep 1 && zutest

  


